---
abstract: 'we are Australian CPAN authors'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Australian
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Acme::CPANAuthors::Australian:
    file: lib/Acme/CPANAuthors/Australian.pm
    version: 0.002
requires:
  Acme::CPANAuthors: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Acme-CPANAuthors-Australian/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-CPANAuthors-Australian
  homepage: https://metacpan.org/release/Acme-CPANAuthors-Australian
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-acme-cpanauthors-australian
version: 0.002
